### ISSUE TITLE
Describe each Sub Topic in detail

### ISSUE THREAD

**Issue by Mavro-Aspro** [Mavro-And-Aspro-Company/Mavro-And-Aspro-Company.github.io#6]

**Comment by rohitreddygade** [comment]
Description for the Problem/ Opportunity Framing problem solution is being created.

**Comment by rohitreddygade** [comment]
Gatherer required link and thoughts process.

**Comment by Mavro-Aspro** [comment]
Have to more descriptive and in detail explanation, and some sub topics are not completed.

**Comment by Mavro-Aspro** [comment]
PDA Doc-Version 1.0 - https://app.box.com/s/m1e273k8tpxgldw0cw8soozomgc069b6
